logger:
  name: "Archimedes"
  logger_path: "/home/nvidia/arch_ws/src/dlio_logger/data/"
  sample_rate: 30
  point_types:
    - 'id'
    - 'ros_time'
    - 'mocap_x'
    - 'mocap_y'
    - 'mocap_z'
    - 'linear_accel_x'
    - 'linear_accel_y'
    - 'linear_accel_z'
    - 'angular_vel_x'
    - 'angular_vel_y'
    - 'angular_vel_z'
    - 'orientation_x'
    - 'orientation_y'
    - 'orientation_z'
    - 'orientation_w'
    - 'mag_x'
    - 'mag_y'
    - 'mag_z'
    - 'pressure'
    - 'roll'
    - 'pitch'
    - 'yaw'
    
  windows:
    - 10
    - 25
    - 50

external:
  use: True
  point_types:
    - 'ex_linear_accel_x'
    - 'ex_linear_accel_y'
    - 'ex_linear_accel_z'
    - 'ex_angular_vel_x'
    - 'ex_angular_vel_y'
    - 'ex_angular_vel_z'
    - 'ex_orientation_x'
    - 'ex_orientation_y'
    - 'ex_orientation_z'
    - 'ex_orientation_w'
    - 'ex_mag_x'
    - 'ex_mag_y'
    - 'ex_mag_z'
    - 'ex_roll'
    - 'ex_pitch'
    - 'ex_yaw'
