logger:
  name: "Archimedes"
  logger_path: "/home/jason/arch_ws/src/dlio_logger/data/"
  sample_rate: 30
  point_types:
    - 'id'
    - 'ros_time'
    - 'mocap_x'
    - 'mocap_y'
    - 'mocap_z'
    - 'linear_accel_x'
    - 'linear_accel_y'
    - 'linear_accel_z'
    - 'angular_vel_x'
    - 'angular_vel_y'
    - 'angular_vel_z'
    - 'orientation_x'
    - 'orientation_y'
    - 'orientation_z'
    - 'orientation_w'
    - 'mag_x'
    - 'mag_y'
    - 'mag_z'
    - 'pressure'
    - 'roll'
    - 'pitch'
    - 'yaw'
    
  windows:
    - 10
    - 25
    - 50

xsens:
  use: True
  point_types:
    - 'xs_linear_accel_x'
    - 'xs_linear_accel_y'
    - 'xs_linear_accel_z'
    - 'xs_angular_vel_x'
    - 'xs_angular_vel_y'
    - 'xs_angular_vel_z'
    - 'xs_orientation_x'
    - 'xs_orientation_y'
    - 'xs_orientation_z'
    - 'xs_orientation_w'
    - 'xs_accel_x'
    - 'xs_accel_y'
    - 'xs_accel_z'
    - 'xs_mag_x'
    - 'xs_mag_y'
    - 'xs_mag_z'
    - 'xs_roll'
    - 'xs_pitch'
    - 'xs_yaw'
